apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    env: production
    author: "Yuncong-Zhang"
    application_type: ui
    release-version: "1.0"
spec:
  containers:
    - name: helloworld
      image: karthequian/helloworld:latest
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
