apiVersion: batch/v1
kind: Job
metadata:
  name: finalcountdown
spec:
  template:
    metadata:
      name: finalcountdown
    spec:
      containers:
      - name: counter
        image: busybox
        command:
        - /bin/sh
        - -c
        - "for i in 9 8 7 6 5 4 3 2 1 ; do sleep 10; echo $i; done"
      restartPolicy: Never
