apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretreader
spec:
  selector:
    matchLabels:
      app: secretreader
  template:
    metadata:
      labels:
        app: secretreader
    spec:
      containers:
      - name: secretreader
        env:
        - name: api_key
          valueFrom:
            secretKeyRef:
              key: api_key
              name: apikey
        image: karthequian/secretreader:latest
        resources:
          limits:
            memory: 64Mi
            cpu: 100m
